# Generated by Django 5.1.6 on 2025-03-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
