# Generated by Django 5.1.6 on 2025-03-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_notes_public"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notes",
            old_name="public",
            new_name="is_public",
        ),
    ]
